@host = https://api.resourcewatch.org/v1
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzcwOTBiZTU5MTU5NmYyN2MxOThjYSIsInJvbGUiOiJBRE1JTiIsInByb3ZpZGVyIjoibG9jYWwiLCJlbWFpbCI6IkNhcmxvcy5EZWxSZWFsLjVAd3JpY29uc3VsdGFudC5vcmciLCJleHRyYVVzZXJEYXRhIjp7ImFwcHMiOlsicnciLCJhcXVlZHVjdCIsImFxdWVkdWN0LXdhdGVyLXJpc2siXX0sImNyZWF0ZWRBdCI6MTY4Njc3NTUyNTAyNSwicGhvdG8iOiJodHRwczovL3MzLmFtYXpvbmF3cy5jb20vd3JpLWFwaS1iYWNrdXBzL3Jlc291cmNld2F0Y2gvc3RhZ2luZy9wcm9maWxlcy9hdmF0YXJzLzAwMC8wMDAvMjU4L29yaWdpbmFsL2RhdGE_MTY3NDA2ODA0NyIsIm5hbWUiOiJDYXJsb3MgRGVsIFJlYWwiLCJpYXQiOjE2ODY3NzU1MjV9.3J7HR6Et_5wmJbbfjnh_7ZvrClzIsRAdwaqMJEMmOuM


PATCH  {{host}}/dataset/0f2cec21-135b-4e2c-8cf8-79e8c2070284/layer/035384c9-fc57-4db5-95d0-b17357520040
Content-Type: application/json
Authorization: {{token}}

{
   "name":"Baseline water stress future provinces",
   "application":[
      "aqueduct"
   ],
   "provider":"cartodb",
   "layerConfig": {
    "account": "wri-rw",
    "params_config": [
      {
         "required":true,
         "key":"period"
      },
      {
         "required":true,
         "key":"scenario"
      }
    ],
    "sql_config": [
      {
        "key": "and",
        "key_params": [
          {
            "key": "year",
            "required": true
          },
          {
            "key": "scenario",
            "required": true
          }
        ]
      },
      {
        "key": "where",
        "key_params": [
          {
            "key": "iso",
            "required": false
          },
          {
            "key": "crop",
            "required": false
          },
          {
            "key": "irrigation",
            "required": false
          },
          {
            "key": "rank",
            "required": false
          }
        ]
      }
    ],
    "body": {
      "maxzoom": 18,
      "minzoom": 3,
      "layers": [
        {
          "type": "cartodb",
          "options": {
            "sql": "with province as (SELECT * FROM aqueduct_results_province_future_2023 WHERE indicator_name = 'bws' AND weight = 'Tot' AND period = {{period}} AND scenario = '{{scenario}}'), \n      country as (SELECT 1000000 + cartodb_id as cartodb_id, the_geom, the_geom_webmercator, null as gid_1, gid_0 as iso, name_0, \n                         null as name_1, null as indicator_name, null::numeric as score, null::numeric as cat, null as label, null as isoc  \n                  FROM gadm_wri_0)\n\nSELECT * FROM country\nUNION ALL\nSELECT a.cartodb_id, a.the_geom, a.the_geom_webmercator,  r.gid_1, null as iso, coalesce(NULLIF(r.name_0,''), 'No Data') as name_0, \n       coalesce(NULLIF(r.name_1,''), 'No Data') as name_1, r.indicator_name, r.score, \n       coalesce(r.cat, -9999) as cat, \n       (CASE WHEN label = 'NoData' THEN 'No Data' ELSE coalesce(NULLIF(r.label,''), 'No Data') END) as label, r.gid_0 as isoc\nFROM gadm_wri a  \nLEFT JOIN province r on a.gid_1 = r.gid_1",
            "cartocss": "#layer{ polygon-comp-op:dst-atop; line-comp-op:dst-atop; polygon-fill:transparent;line-color:transparent;polygon-opacity: 1;  line-width: 1; line-opacity: 1;} #layer{ polygon-fill:ramp([cat], (#990000,#FF1900,#FF9900, #FFE600,#FFFF99,#4E4E4E,#4E4E4E), (4,3,2,1,0,-1,-9999), '='); \n        line-color:ramp([cat], (#990000,#FF1900,#FF9900, #FFE600,#FFFF99,#4E4E4E,#4E4E4E), (4,3,2,1,0,-1,-9999), '=');}\n\n#layer[iso!=null] {\n  polygon-fill:transparent; polygon-opacity: 1;\n line-color:#CFCFCB; line-width: 1; line-opacity: 1;polygon-comp-op:dst-over; \n\n}\n\n#layer[isoc='{{iso}}'] {\n line-color:#CFCFCB; line-width: 1; line-opacity: 1;  polygon-comp-op:dst-atop;\n\n}\n\n#layer[iso='{{iso}}'] { line-color:  #2e2c2c ;line-width: 1.5; polygon-opacity: 0;   line-comp-op:dst-over;}",
            "cartocss_version": "2.3.0"
          }
        }
      ]
    }
  },
  "legendConfig": {
    "disclaimer": [
      {
        "color": "#4E4E4E",
        "name": "No data"
      }
    ],
    "items": [
      {
        "color": "#FFFF99",
        "value": "(0-1)",
        "name": "Low"
      },
      {
        "color": "#FFE600",
        "value": "(1-2)",
        "name": "Low-medium"
      },
      {
        "color": "#FF9900",
        "value": "(2-3)",
        "name": "Medium-high"
      },
      {
        "color": "#FF1900",
        "value": "(3-4)",
        "name": "High"
      },
      {
        "color": "#990000",
        "value": "(4-5)",
        "name": "Extremely-high"
      }
    ],
    "type": "choropleth"
  },
  "interactionConfig": {
    "output": [
      {
        "column": "name_0",
        "format": null,
        "prefix": "",
        "property": "Country",
        "suffix": "",
        "type": "string"
      },
      {
        "column": "name_1",
        "format": null,
        "prefix": "",
        "property": "Province",
        "suffix": "",
        "type": "string"
      },
      {
        "column": "label",
        "format": null,
        "prefix": "",
        "property": "Category",
        "suffix": "",
        "type": "string"
      },
      {
        "column": "score",
        "format": null,
        "prefix": "",
        "property": "Score",
        "suffix": "",
        "type": "numeric"
      }
    ]
  }
}