### layer
GET https://api.resourcewatch.org/v1/dataset/39fec76b-2bba-4d5c-aa02-0283be6be91a/layer



# with r as (
#   SELECT 
#     * 
#   FROM 
#     country_baseline_aqueduct40 
#   WHERE 
#     indicator_name = 'bws' 
#     and weight = 'Tot'
# ) SELECT
# a.the_geom, 
# a.the_geom_webmercator, 
# a.cartodb_id, 
# r.gid_0, 
# coalesce(
#   NULLIF(r.name_0, ''), 
#   'No Data'
# ) as name_0, 
# r.indicator_name, 
# r.score, 
# coalesce(r.cat, -9999) as cat, 
# \n (
#   CASE WHEN label = 'NoData' THEN 'No Data' ELSE coalesce(
#     NULLIF(r.label, ''), 
#     'No Data'
#   ) END
# ) as label\nFROM gadm_wri_0 a \nLEFT 
# JOIN r on a.gid_0 = r.gid_0\nWHERE a.gid_0 != 'ATA'

### country ranking base
GET https://wri-rw.carto.com/api/v2/sql?q=SELECT * FROM country_baseline_aqueduct40 WHERE indicator_name = 'bws' and weight = 'Tot'


### country ranking base line future
GET https://wri-rw.carto.com/api/v2/sql?q=with r as (SELECT * FROM aqueduct_results_country_future_2023 WHERE indicator_name = 'bws' AND scenario = 'opt' AND weight = 'Tot' AND period = 2030) SELECT a.the_geom, a.the_geom_webmercator, a.cartodb_id, r.gid_0, coalesce(NULLIF(r.name_0, ''), 'No Data') as name_0, r.indicator_name, r.score, coalesce(r.cat, -9999) as cat, (CASE WHEN label = 'NoData' THEN 'No Data' ELSE coalesce(NULLIF(r.label, ''), 'No Data') END) as label FROM gadm_wri_0 a LEFT JOIN r on a.gid_0 = r.gid_0 WHERE a.gid_0 != 'ATA'



### country ranking base
GET https://wri-rw.carto.com/api/v2/sql?q=with r as (SELECT * FROM country_baseline_aqueduct40 WHERE indicator_name = 'bws' and weight = 'Tot') SELECT a.the_geom, a.the_geom_webmercator, a.cartodb_id, r.gid_0, coalesce(NULLIF(r.name_0, ''), 'No Data') as name_0, r.indicator_name, r.score, coalesce(r.cat, -9999) as cat, (CASE WHEN label = 'NoData' THEN 'No Data' ELSE coalesce(NULLIF(r.label, ''), 'No Data') END) as label FROM gadm_wri_0 a LEFT JOIN r on a.gid_0 = r.gid_0 WHERE a.gid_0 != 'ATA'


### regional ranking base
GET https://wri-rw.carto.com/api/v2/sql?q=with province as (SELECT * FROM province_baseline_aqueduct40 WHERE indicator_name = 'bws' and weight = 'Tot'), country as (SELECT 1000000 + cartodb_id as cartodb_id, the_geom, the_geom_webmercator, null as gid_1, gid_0 as iso, name_0, null as name_1, null as indicator_name, null :: numeric as score, null :: numeric as cat, null as label, null as isoc FROM gadm_wri_0) SELECT * FROM country UNION ALLSELECT a.cartodb_id, a.the_geom, a.the_geom_webmercator, r.gid_1, null as iso, coalesce(NULLIF(r.name_0, ''), 'No Data') as name_0, coalesce(NULLIF(r.name_1, ''), 'No Data') as name_1, r.indicator_name, r.score, coalesce(r.cat, -9999) as cat, (CASE WHEN label = 'NoData' THEN 'No Data' ELSE coalesce(NULLIF(r.label, ''), 'No Data') END) as label, r.gid_0 as isoc FROM gadm_wri a LEFT JOIN province r on a.gid_1 = r.gid_1

